### ISSUE TITLE
Separate Optargs

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#37]
Per #34, we need to separate optargs as being either runtime variable setters or actions/commands.

The Bash script did this by iterating over the optargs twice, once for setters, once for actions.

How should we best handle this?

Should the GUI app be made into one panel rather than two, by making "install" an option on the control panel?

**Comment by n8marti** [comment]
For the GUI there still needs to be 2 windows, but it could be made to start with the "Control Panel" window and there include an "Install" button that would open the "Install" window. I think that should be a separate PR from separating the optarg logic, though, because they're separate problems to solve.
